---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kernel-syncdata-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: kernel-syncdata-service
    spec:
      containers:
      - name: kernel-syncdata-service
        image: docker-registry.mosip.io:5000/kernel-syncdata-service
        env:
        - name: active_profile_env
          value: dev
          name: spring_config_label_env
          value: 0.8.0
          name: spring_config_url_env
          value: http://104.211.212.28:51000
        ports:
        - containerPort: 8089
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: kernel-syncdata-service
spec:
  ports:
    - port: 8089
  selector:
    app: kernel-syncdata-service

