---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kernel-masterdata-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: kernel-masterdata-service
    spec:
      initContainers:
      - name: wait-for-config-server
        image: centos:centos7
        command: [ "sh", "-c"]
        args:
        - while [ $(curl -sw '%{http_code}' $spring_config_url_env/actuator/health -o /dev/null) -ne 200 ]; do
            echo "config server not up at address $spring_config_url_env sleeping for 15 secs" ;
            sleep 15;
          done;
        env:
         - name: spring_config_url_env
           value: http://104.211.212.28:51000
      containers:
      - name: kernel-masterdata-service
        image: docker-registry.mosip.io:5000/kernel-masterdata-service
        env:
        - name: active_profile_env
          value: dev
        - name: spring_config_label_env
          value: 0.12.0_ADMIN
        - name: spring_config_url_env
          value: http://104.211.212.28:51000
        ports:
        - containerPort: 8086
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: kernel-masterdata-service
spec:
  ports:
    - port: 8086
  selector:
    app: kernel-masterdata-service

