---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kernel-packetserver-http
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: kernel-packetserver-http
    spec:
      containers:
      - name: kernel-packetserver-http
        image: docker-registry.mosip.io:5000/kernel-packetserver-http:349
        env:
        - name: active_profile_env
          value: dev-k8
        ports:
        - containerPort: 8082
        volumeMounts:
        - mountPath: "/mosip"
          name: volume
        imagePullPolicy: Always
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: kernel-packetserver-http
spec:
  ports:
    - port: 8082
  selector:
    app: kernel-packetserver-http

