swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'integ.mosip.io:443'
basePath: /batchjob
tags:
  - name: Services for batch job
    description: Batch Service Controller
paths:
  /v0.1/pre-registration/batch/state/consumedStatus:
    put:
      tags:
        - Services for batch job
      summary: consumedAppointments
      operationId: consumedAppointmentsUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MainResponseDTO«string»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /v0.1/pre-registration/batch/state/expiredStatus:
    put:
      tags:
        - Services for batch job
      summary: expiredAppointments
      operationId: expiredAppointmentsUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MainResponseDTO«string»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  ExceptionJSONInfoDTO:
    type: object
    properties:
      errorCode:
        type: string
      message:
        type: string
    title: ExceptionJSONInfoDTO
  MainResponseDTO«string»:
    type: object
    properties:
      err:
        description: Error Details
        $ref: '#/definitions/ExceptionJSONInfoDTO'
      status:
        type: boolean
        description: Response Status
      resTime:
        type: string
        description: Response Time
      response:
        type: string
        description: Response
    title: MainResponseDTO«string»