swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'integ.mosip.io:443'
basePath: /notification
tags:
  - name: notification-controller
    description: Notification Controller
paths:
  /v0.1/pre-registration/generateQRCode:
    post:
      tags:
        - notification-controller
      summary: generateQRCode
      operationId: generateQRCodeUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: data
          description: data
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MainResponseDTO«QRCodeResponseDTO»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /v0.1/pre-registration/notification:
    post:
      tags:
        - notification-controller
      summary: Trigger notification
      operationId: sendNotificationUsingPOST
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: NotificationDTO
          description: NotificationDTO
          required: true
          schema:
            type: string
        - name: file
          in: formData
          description: file
          required: false
          type: file
        - in: formData
          name: langCode
          description: langCode
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MainResponseDTO«NotificationDTO»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  ExceptionJSONInfoDTO:
    type: object
    properties:
      errorCode:
        type: string
      message:
        type: string
    title: ExceptionJSONInfoDTO
  InputStream:
    type: object
    title: InputStream
  MainResponseDTO«NotificationDTO»:
    type: object
    properties:
      err:
        description: Error Details
        $ref: '#/definitions/ExceptionJSONInfoDTO'
      status:
        type: boolean
        description: Response Status
      resTime:
        type: string
        description: Response Time
      response:
        description: Response
        $ref: '#/definitions/NotificationDTO'
    title: MainResponseDTO«NotificationDTO»
  MainResponseDTO«QRCodeResponseDTO»:
    type: object
    properties:
      err:
        description: Error Details
        $ref: '#/definitions/ExceptionJSONInfoDTO'
      status:
        type: boolean
        description: Response Status
      resTime:
        type: string
        description: Response Time
      response:
        description: Response
        $ref: '#/definitions/QRCodeResponseDTO'
    title: MainResponseDTO«QRCodeResponseDTO»
  NotificationDTO:
    type: object
    properties:
      appointmentDate:
        type: string
      appointmentTime:
        type: string
      emailID:
        type: string
      mobNum:
        type: string
      name:
        type: string
      preId:
        type: string
    title: NotificationDTO
  QRCodeResponseDTO:
    type: object
    properties:
      qrcode:
        type: string
        format: byte
    title: QRCodeResponseDTO