apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress  
  annotations:    
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/proxy-body-size: "50m"
spec:  
  rules:
  - http:
      paths:
      - path: /uingenerator
        backend:
          serviceName: kernel-uingenerator-service
          servicePort: 8080
      - path: /applicanttype
        backend:
          serviceName: kernel-applicanttype-service
          servicePort: 8094
      - path: /auditmanager
        backend:
          serviceName: kernel-auditmanager-service
          servicePort: 8081
      - path: /otpnotifier
        backend:
          serviceName: kernel-otpnotification-service
          servicePort: 8082
      - path: /emailnotifier
        backend:
          serviceName: kernel-emailnotification-service
          servicePort: 8083
      - path: /smsnotifier
        backend:
          serviceName: kernel-smsnotification-service
          servicePort: 8084
      - path: /otpmanager
        backend:
          serviceName: kernel-otpmanager-service
          servicePort: 8085
      - path: /masterdata
        backend:
          serviceName: kernel-masterdata-service
          servicePort: 8086
      - path: /cryptomanager
        backend:
          serviceName: kernel-cryptomanager-service
          servicePort: 8087
      - path: /keymanager
        backend:
          serviceName: kernel-keymanager-service
          servicePort: 8088
      - path: /syncdata
        backend:
          serviceName: kernel-syncdata-service
          servicePort: 8089
      - path: /idrepo
        backend:
          serviceName: kernel-idrepo-service
          servicePort: 8090
      - path: /authmanager
        backend:
          serviceName: kernel-auth-service
          servicePort: 8091
      - path: /ldapmanager
        backend:
          serviceName: kernel-ldap-service
          servicePort: 8092
      - path: /licensekeymanager
        backend:
          serviceName: kernel-licensekeymanager-service
          servicePort: 8093
      - path: /pre-registration/v1.0/auth
        backend:
          serviceName: pre-registration-auth-service
          servicePort: 9090
      - path: /pre-registration/v1.0/demographic
        backend:
          serviceName: pre-registration-demographic-service
          servicePort: 9092
      - path: /pre-registration/v1.0/document
        backend:
          serviceName: pre-registration-document-service
          servicePort: 9093
      - path: /pre-registration/v1.0/sync
        backend:
          serviceName: pre-registration-datasync-service
          servicePort: 9094
      - path: /pre-registration/v1.0/booking
        backend:
          serviceName: pre-registration-booking-service
          servicePort: 9095
      - path: /pre-registration/v1.0/batchjob
        backend:
          serviceName: pre-registration-batchjob-service
          servicePort: 9096
      - path: /pre-registration/v1.0/translitration
        backend:
          serviceName: pre-registration-translitration-service
          servicePort: 9098
      - path: /pre-registration/v1.0/notification
        backend:
          serviceName: pre-registration-notification-service
          servicePort: 9099
      - path: /identity
        backend:
          serviceName: authentication-service
          servicePort: 8090
      - path: /pre-registration-ui
        backend:
          serviceName: pre-registration-ui
          servicePort: 80
      - path: /bio-dedupe
        backend:
          serviceName: registration-processor-packet-bio-dedupe-service
          servicePort: 9097
      - path: /abis
        backend:
          serviceName: registration-processor-abis
          servicePort: 9098
      - path: /registration-connector
        backend:
          serviceName: registration-processor-connector-stage
          servicePort: 8091 
      - path: /nginx
        backend:
          serviceName: sample-nginx
          servicePort: 80 
          
      
          
