---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pre-registration-ui
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: pre-registration-ui
    spec:
      containers:
      - name: pre-registration-ui
        image: docker-registry.mosip.io:5000/pre-registration-ui
        env:
        - name: active_profile_env
          value: dev-k8
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: pre-registration-ui
spec:
  ports:
    - port: 80
  selector:
    app: pre-registration-ui