---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registration-processor-external-integration-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: registration-processor-external-integration-service
    spec:
      containers:
      - name: registration-processor-external-integration-service
        image: docker-registry.mosip.io:5000/registration-processor-external-integration-service
        ports:
          - name: verticle-port
            containerPort: 8201
        env:
        - name: active_profile_env
          value: dev
        - name: spring_config_label_env
          value: 0.10.0
        - name: spring_config_url_env
          value: http://kernel-config-server:51000/config
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: registration-processor-external-integration-service
spec:
  ports:
    - port: 8201
  selector:
    app: registration-processor-external-integration-service

