---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registration-processor-packet-bio-dedupe-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: registration-processor-packet-bio-dedupe-service
        component: service-hazelcast-server
    spec:
      containers:
      - name: registration-processor-packet-bio-dedupe-service
        image: docker-registry.mosip.io:5000/packet-bio-dedupe-service
        ports:
          - name: eventbus-port
            containerPort: 5711
        ports:
          - name: hazelcast-port
            containerPort: 5701
        ports:
          - name: verticle-port
            containerPort: 9097
        env:
        - name: active_profile_env
          value: dev
        - name: spring_config_label_env
          value: 0.9.0
        - name: spring_config_url_env
          value: http://104.211.212.28:51000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: registration-processor-packet-bio-dedupe-service
spec:
  ports:
    - port: 9097
  selector:
    app: registration-processor-packet-bio-dedupe-service

